# fly.toml app configuration file generated for eagy on 2023-04-19T22:11:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eagy"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
